name: deployment
on:
  push:
    branches:
      -develop
job: 
   build deploy:
   runs-on: ubantu-latest
   steps:
     -name: checkout repository
      uses: actions/checkout@v4
     -name: build website 
      run:
        npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
     -name: upload pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./dist"
        name: "develop artifacts"
    workflows_develop_job:
    needs: wf-develop-build_job
      permisions:
        pages: write
        id-token: write
      environment: "development env"
      runs-on: ubantu latest
      steps:
        -name: deploy buildartifacts on pages
         uses: artifacts/deploy-pages@v4
         with:
             artifacts_name: "develop-artifacts:"
             

